<a href="https://colab.research.google.com/github/Ram-Pasupula/torch/blob/main/torch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
a = torch.arange(10)

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape(2,-1)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a[:]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = torch.rand(4,4)
b

tensor([[0.7420, 0.2561, 0.2734, 0.3707],
        [0.9097, 0.9253, 0.7163, 0.2401],
        [0.8638, 0.8235, 0.4833, 0.9592],
        [0.7281, 0.0525, 0.5729, 0.3718]])

In [ ]:
b[:,1]


tensor([0.8272, 0.5149])

In [ ]:
b[:,1:]

tensor([[0.2561, 0.2734, 0.3707],
        [0.9253, 0.7163, 0.2401],
        [0.8235, 0.4833, 0.9592],
        [0.0525, 0.5729, 0.3718]])

In [ ]:
b[1]

tensor([0.9097, 0.9253, 0.7163, 0.2401])